### ISSUE TITLE
Codigo tuc no acepta enteros

### ISSUE THREAD

**Issue by oscarmcm** [nodenica/node-tuc#5]
```js
    var number = 34343434;
    tuc.getType(number.toString(), function( type ){ console.log(type); });
   // retorna error
```

Seria mas facil validar el largo del string en ves de usar regex que acepta solo string y luego verifica el largo

**Comment by paulomcnally** [comment]
Te tiras el fix?

**Comment by paulomcnally** [comment]
@oscarmcm que esperarías como respuesta?

Si vos haces:

    var number = 00758888;
    console.log(number);

Te retorna:

    758888

Los dos ceros delante del número desaparecen porque se convierte en un entero positivo.

Lo mismo pasa al agregarle el .toString().

Entonces dejan de tener 8 dígitos.

Cuando vos envias un parámetro via argv, query, post... este se envia como string, no se me ocurre un escenario donde se envíe como un entero.

**Comment by oscarmcm** [comment]
@paulomcnally sip lo acabo de corregir en el cli :+1:
