### ISSUE TITLE
NPM Collaborators

### ISSUE THREAD

**Issue by paulomcnally** [nodenica/node-tuc#6]
Chicos, ustedes han colaborado en este repo, me gustaria saber si desean mantenerlo (entre todos mantenerlo).

Si aceptan los agregaria como colaboradores en https://www.npmjs.com/package/tuc.

De esta forma ustedes podria actualizar el modulo en NMP en caso de que agreguen caracteristicas.

Solo requiero sus usuarios en www.npmjs.com

Cc: @hosmelq @BruceLampson @oscarmcm @robe007

Saludos

**Comment by oscarmcm** [comment]
https://www.npmjs.com/~oscarmcm

**Comment by paulomcnally** [comment]
✓done

    $ npm owner add oscarmcm tuc

**Comment by hosmelq** [comment]
https://www.npmjs.com/~hosmelq

**Comment by paulomcnally** [comment]
✓done

    $ npm owner add hosmelq tuc

**Comment by BruceLampson** [comment]
https://www.npmjs.com/~brucelampson

2016-01-02 21:51 GMT-06:00 Paulo McNally <notifications@github.com>:

**Comment by paulomcnally** [comment]
✓done

    $ npm owner add brucelampson tuc
